### ISSUE TITLE
prettier formatter not work if there is a prettier-vscode config file

### ISSUE THREAD

**Issue by phenix3443** [juanfranblanco/vscode-solidity#417]
solidity version: v0.0.165
[prettier-vscode](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)  version: v.10.1.0
prettier-vscode config:
```yaml
plugins:
  - prettier-plugin-solidity
overrides:
  - files: "**/*.sol"
    options:
      # parser: solidity-parse
      tabWidth: 2
      useTabs: false
      singleQuote: false
      bracketSpacing: false
      explicitTypes: always
```

test solidity file:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

contract Counter {
    uint256 public number;

    function set(uint256 num) public {
        number = num;
    }

    function incr() public {



        number++;
    }
}
```

1. this file should be formatted on save, but prettier not work, 
2. the prettier icon in status bar seems has something wrong.
<img width="332" alt="image" src="https://github.com/juanfranblanco/vscode-solidity/assets/1721532/47de95ac-0e44-4e63-b98f-dae4b75159ef">

thanks for your help!!
