### ISSUE TITLE
Deployment using the configured environment settings as per EIP82

### ISSUE THREAD

**Issue by juanfranblanco** [juanfranblanco/vscode-solidity#5]
Using the configuration settings using the package file as per EIP82

``` yaml
environments:
  morden:
    objects:
      auth_factory1:
        class: DSAuthFactory
        address: '0x7639a37b8ecbd68e15b8e173897c6c0dea462452'
```

We should be able to deploy to Live, Morden, Cloud (Strato), Package Manager (npm) etc etc
